### ISSUE TITLE
[AutoComplete] 자동완성 이벤트 처리

### ISSUE THREAD

**Issue by silee9019** [2sangin/posthangle#24]
- [x] 한글 처리, 버퍼 이원화해서 해결
- [x] 오토컴플릿 단어 입력 중인 상태 표시하기 (단어에 점선 테두리 같은 방식으로)
  - [x] 알파벳 입력시 제대로 표시하기
- [x] 좌우 방향키 처리하기
- [x] 상하 방향키 처리하기
- [x] Tab 혹은 Ctrl + Space 처리하기
  - 입력시 팝업 리스트에서 선택된 단어를 TextPane에 넣어주고, DB 카운트 증가하기

**Comment by silee9019** [comment]
committed 단어 버퍼, uncommitted 단어 버퍼 별도로 두어서 관리하면 될듯함

**Comment by 2sangin** [comment]
한글 입력 받는 문제는 해결
* 오토컴플릿 단어 입력 중인 상태 표시하기 (단어에 점선 테두리 같은 방식으로)
* 좌우 방향키 처리하기
* 상하 방향키 처리하기
* Tab 혹은 Enter 입력시 팝업 리스트에서 선택된 단어를 TextPane에 넣어주고, DB 카운트 증가하기
